name: go build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'

    - name: Go Mod
      run: go mod download
    - name: Build
      run: go build -v ./...
    - name: Test
      run: go test -v -json > testresults.json ./...
    - name: Upload test results
      uses: actions/upload-artifact@v4
      with:
        name: Results
        path: testresults.json
